[project]
name = "shift-maker"
version = "0.1.0"
description = "shift maker using google form and google spread sheet"
readme = "README.md"
requires-python = ">=3.11,<4"
dependencies = [
    "gspread>=6.2.1,<7",
    "pandas>=3.0.5,<4",
    "ruamel.yaml>=0.19.1,<0.20",
    "gspread-dataframe>=4.0.0,<5",
    "pulp>=3.3.2,<4",
]

[tool.uv]
package = false
